name: Deploy to Production

on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Fake deployment
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
          token: ${{ secrets.ALL_REPO_PAT }}

      - name: Test Deployment
        run: |
          echo "running test job 2"
          echo "github.action_ref: $(git describe --tags --abbrev=0)"