name: Deploy to Production

on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Fake deployment
    steps:
      - name: Test Deployment
        run: |
          echo "running test job 2"
          echo "github.action_ref: $(git describe --tags --abbrev=0)"